apiVersion: apps/v1
kind: Deployment
metadata: 
  name: set
  labels:
    project: epense
    environment: dev
spec:
  replicas: 3
  selector: 
    matchLabels:
      project: epense
      environment: dev   
  template:
    metadata:
      labels:
        project: epense
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:   
  name: svc
  labels:
    project: epense
    environment: dev
spec:
  selector:
    project: epense
    environment: dev
  ports:
  - name: svc-port
    protocol: TCP
    port: 80
    targetPort: 80