apiVersion: v1
kind: Pod
metadata: 
  name: expense
  annotations:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    env:  
      - name: project
      valueFrom:
        configMapKeyRe:
          name: expense
          key: project