apiVersion: v1
kind: Pod
metadata: 
  name: expense
  annotations:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:  
        cpu: 100m
        memory: 120Mi
      limits: 
        cpu: 120m
        memory: 130Mi