apiVersion: v1
kind: Pod
metadata: 
  name: expense
  annotations:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - ConigMapRef
      name: expense
        
