apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: expense
    environment: dev
    module: something
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    module: something

  ports:
  - name: svc-port
    protocol: TCP
    port: 80
    targetPort: 80   